#!/usr/bin/env python3
"""Outline the BeCurrent wordmark into SVG paths.

Writes assets/images/brand/*.svg and assets/favicon.svg from the vendored
Playfair Display in assets/fonts/. Run it from the repository root:

    pip install fonttools brotli
    python3 scripts/brand/build-wordmark.py

Why the mark is paths and not <text>: an SVG loaded through an <img> cannot
reach a webfont, and a <text> element that falls back to whatever serif the
machine has stops being the brand mark. Outlines render identically on a
Chromebook, a projector, and a browser tab, which is the whole point of a logo.

Why it is Python and off the test path: reading a woff2 needs fontTools and
brotli, and `validate.js` has to stay runnable on a bare checkout with no
install at all. The four SVGs are committed, so nothing in the build or the
gate depends on this file. It exists so the mark can be redrawn rather than
only inherited: change a constant below, rerun it, and the whole set moves
together.

The construction, so the numbers mean something:

  * Playfair Display, the variable weight axis instanced twice. It is a
    high-contrast masthead serif, which is the face the supplied artwork is
    set in and the reason the site's headings now match the logo.
  * The full caps B and C are wght 700. The small caps are separate glyphs
    scaled to 0.72 of cap height and instanced at wght 800, because scaling a
    700 capital down thins its stems next to a full-size one. The compensation
    is what keeps the stroke weight even across the word.
  * The red C is drawn at 1.10, so it breaks the cap line above and the
    baseline below. That overshoot is the mark's only piece of drama and it is
    deliberate: it is what makes "Current" the word you read first.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'assets', 'fonts', 'playfair-display-latin-wght-normal.woff2')
OUT = os.path.join(ROOT, 'assets', 'images', 'brand')

CAP_W = 700     # weight of the full caps
SC_W = 800      # weight of the small caps, compensating for being scaled down
SC = 0.72       # small-cap height, as a fraction of cap height
CSCALE = 1.10   # the red C, relative to the B
TRACK = 6       # letterspacing, per mille of the em

RED = '#D62B1F'      # --signal
PAPER = '#FFFFFF'    # the wordmark on a dark ground
INK = '#14171A'      # --ink, the wordmark on a light ground
PLATE = '#16181B'    # --slate-900

# B  E(sc)  C(red)  U R R E N T(sc)
RUN = [('B', 1.0, 'w'), ('E', SC, 'sc'), ('C', CSCALE, 'r'),
       ('U', SC, 'sc'), ('R', SC, 'sc'), ('R', SC, 'sc'),
       ('E', SC, 'sc'), ('N', SC, 'sc'), ('T', SC, 'sc')]

HEAD = """<!-- The BeCurrent wordmark. Generated by scripts/brand/build-wordmark.py:
     Playfair Display, full caps at wght 700 with small caps scaled to {sc} of cap
     height at wght 800, and the C at {c} so it breaks the cap line. Converted to
     paths on purpose, because an SVG in an <img> cannot load a webfont.
     Width and height are set explicitly, per the image contract in CLAUDE.md. -->
""".format(sc=SC, c=CSCALE)


def instance(weight):
    return instancer.instantiateVariableFont(TTFont(SRC), {'wght': weight}, inplace=True)


def draw(font, ch, scale, dx):
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord(ch)]
    # Font space is y-up and SVG is y-down, so the y scale is negated and the
    # baseline lands on y=0.
    t = Transform(scale, 0, 0, -scale, dx, 0)
    pen = SVGPathPen(glyphs, ntos=lambda v: f'{v:.1f}')
    glyphs[name].draw(TransformPen(pen, t))
    bounds = BoundsPen(glyphs)
    glyphs[name].draw(TransformPen(bounds, t))
    return pen.getCommands(), glyphs[name].width * scale, bounds.bounds


def build():
    caps, smalls = instance(CAP_W), instance(SC_W)
    x = 0.0
    white, red, box = [], [], [1e9, 1e9, -1e9, -1e9]
    for ch, scale, kind in RUN:
        d, advance, b = draw(smalls if kind == 'sc' else caps, ch, scale, x)
        (red if kind == 'r' else white).append(d)
        if b:
            box = [min(box[0], b[0]), min(box[1], b[1]),
                   max(box[2], b[2]), max(box[3], b[3])]
        x += advance + TRACK * scale
    return white, red, box


def write(name, body):
    path = os.path.join(OUT, name) if name != 'favicon.svg' else \
        os.path.join(ROOT, 'assets', name)
    with open(path, 'w') as fh:
        fh.write(body)
    print(f'  {os.path.relpath(path, ROOT)}  {len(body)} bytes')


white, red, box = build()
W, H = box[2] - box[0], box[3] - box[1]
shift = f'translate({-box[0]:.1f} {-box[1]:.1f})'


def marks(letters, accent):
    return (f'<g transform="{shift}">'
            f'<path fill="{letters}" d="{" ".join(white)}"/>'
            f'<path fill="{accent}" d="{" ".join(red)}"/></g>')


def wordmark(letters, accent):
    return (f'{HEAD}<svg xmlns="http://www.w3.org/2000/svg" width="{W:.0f}" '
            f'height="{H:.0f}" viewBox="0 0 {W:.1f} {H:.1f}" role="img" '
            f'aria-label="BeCurrent">{marks(letters, accent)}</svg>\n')


os.makedirs(OUT, exist_ok=True)
print(f'wordmark {W:.0f} x {H:.0f}, ratio {W / H:.2f}')

# The wordmark alone, for a masthead or a footer. Two colourways rather than one
# recoloured by CSS: an SVG in an <img> cannot see the page's custom properties,
# and inlining the mark into every page to make currentColor work would put ten
# kilobytes of path data in the markup of every lesson.
write('becurrent-wordmark.svg', wordmark(PAPER, RED))
write('becurrent-wordmark-ink.svg', wordmark(INK, RED))

# The plate, matching the supplied artwork: 10:3, with the mark at 72% of the
# width. This is the shareable logo, the one to hand to Canvas or a slide.
PW, PH = 2000, 600
mw = PW * 0.72
s = mw / W
plate = (f'{HEAD}<svg xmlns="http://www.w3.org/2000/svg" width="{PW}" '
         f'height="{PH}" viewBox="0 0 {PW} {PH}" role="img" aria-label="BeCurrent">'
         f'<rect width="{PW}" height="{PH}" rx="40" fill="{PLATE}"/>'
         f'<g transform="translate({(PW - mw) / 2:.1f} {(PH - H * s) / 2:.1f}) '
         f'scale({s:.4f})">{marks(PAPER, RED)}</g></svg>\n')
write('becurrent-logo.svg', plate)

# The favicon: the one letter that carries the mark, at the size a browser tab
# actually gives you. Red ground under a paper C, which is the strongest pairing
# in the palette and stays legible at 16px against light or dark browser chrome.
# Drawn at wght 900 rather than the wordmark's 700, because Playfair's hairlines
# are the first thing to disappear at 16px and a C whose thin side has vanished
# reads as a bracket.
cfont = instance(900)
d, advance, b = draw(cfont, 'C', 1.0, 0)
cw, ch = b[2] - b[0], b[3] - b[1]
fs = 40.0 / ch
icon = (f'<!-- The BeCurrent mark reduced to its one letter. Generated by\n'
        f'     scripts/brand/build-wordmark.py, the same C outline as the wordmark. -->\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" '
        f'viewBox="0 0 64 64" role="img" aria-label="BeCurrent">'
        f'<rect width="64" height="64" rx="13" fill="{RED}"/>'
        f'<g transform="translate({32 - cw * fs / 2 - b[0] * fs:.1f} '
        f'{32 - ch * fs / 2 - b[1] * fs:.1f}) scale({fs:.4f})">'
        f'<path fill="{PAPER}" d="{d}"/></g></svg>\n')
write('favicon.svg', icon)
