#!/usr/bin/env node
'use strict';

/**
 * The structural gate.
 *
 * Dependency-free and offline by design, so it runs on a bare checkout with no
 * `npm install` at all. The `structure` CI job deliberately does not install
 * anything, which is what keeps that guarantee honest. Anything needing the
 * network belongs in a nightly job, never here: a third party's outage must
 * never fail a commit.
 *
 * What this file is for is the class of bug where every page still looks right.
 * A missing capture block, a storage key that two files disagree about, a data
 * file pointing at a brief instead of its wrapper: all invisible in a browser,
 * all silently lose a student's work. Those are the checks worth having.
 *
 *   node scripts/validate.js
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');

const R = '\x1b[31m', G = '\x1b[32m', C = '\x1b[36m', W = '\x1b[1m', D = '\x1b[2m', X = '\x1b[0m';

const errors = [];
let checks = 0;

function err(file, message) {
  errors.push({ file: path.relative(ROOT, file), message });
}
function ok() { checks++; }
function assert(cond, file, message) {
  checks++;
  if (!cond) errors.push({ file: path.relative(ROOT, file), message });
  return cond;
}
function section(name) { console.log(`\n${C}${W}── ${name}${X}`); }
function done(note) { console.log(`   ${D}${note}${X}`); }

function read(file) {
  try { return fs.readFileSync(file, 'utf8'); } catch (e) { return null; }
}
function glob(dir, re) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => re.test(f)).sort().map(f => path.join(dir, f));
}

// ── Week directories ──────────────────────────────────────────────────────────

const weekDirs = fs.readdirSync(ROOT)
  .filter(f => /^week-\d{2}$/.test(f))
  .filter(f => fs.statSync(path.join(ROOT, f)).isDirectory())
  .sort();

// Unit directories, one per theme. A unit's Briefs are generated by
// scripts/build-units.js from scripts/lib/unit-content/, and a unit is discovered
// from its own content module rather than from a naming convention, so adding a
// theme never requires editing this file.
const unitDirs = (() => {
  const dir = path.join(ROOT, 'scripts', 'lib', 'unit-content');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.js')).map(f => {
    try { return require(path.join(dir, f)).meta.unitKey; } catch (e) { return null; }
  }).filter(k => k && fs.existsSync(path.join(ROOT, k))).sort();
})();

section('Content directories');
assert(weekDirs.length + unitDirs.length > 0, ROOT, 'no week-NN or unit directories found');
done(`${weekDirs.length} week${weekDirs.length === 1 ? '' : 's'} (${weekDirs.join(', ') || 'none'})`
  + ` · ${unitDirs.length} unit${unitDirs.length === 1 ? '' : 's'} (${unitDirs.join(', ') || 'none'})`);

// ── The module set ────────────────────────────────────────────────────────────
//
// The modules are a TOOLKIT, not a checklist. A block uses the ones it needs, and
// how many modules a lesson shows on a given day is a teaching decision that this
// file has no business enforcing. An earlier version asserted "exactly 8, in this
// order" and that was a code of daily conduct wearing a build gate's clothes.
//
// What IS asserted is the plumbing: every module the renderer defines must have
// exactly one way to open, and no id may be defined twice. A module with no
// delivery path is a card a student clicks and nothing happens; a duplicated id is
// a module that silently shadows another. Neither is visible in a browser.
const RENDERER = path.join(ROOT, 'assets', 'js', 'becurrent-week-renderer-v1.js');

section('The module set');
const rendSrc = read(RENDERER);
if (!rendSrc) {
  err(RENDERER, 'renderer not readable');
} else {
  const ids = [];
  // Split the MODULES array on its entry boundaries. A single non-greedy regex
  // over the whole array swallows every entry into the first match, which reports
  // one module with three delivery modes instead of three modules with one each.
  const arr = (rendSrc.match(/const MODULES = \[([\s\S]*?)\n\];/) || [])[1] || '';
  const blocks = arr.split(/\n(?=\s*\{\s*id:)/).filter(b => /id:\s*'/.test(b));
  blocks.forEach(b => {
    const id = (b.match(/id:\s*'([a-z0-9]+)'/) || [])[1];
    if (!id) return;
    assert(!ids.includes(id), RENDERER, `module id '${id}' is defined more than once`);
    ids.push(id);

    const modes = ['render:', 'jump:', 'link:'].filter(k => b.includes(k));
    assert(modes.length === 1, RENDERER,
      `module '${id}' has ${modes.length} delivery modes (${modes.join(', ') || 'none'}). `
      + 'Exactly one of render/jump/link, or the card does nothing when clicked.');
  });

  assert(ids.length > 0, RENDERER, 'the renderer defines no modules');

  // Every render: target must actually exist as a function.
  (rendSrc.match(/render:\s*(\w+)/g) || []).forEach(hit => {
    const fn = hit.replace(/render:\s*/, '');
    assert(rendSrc.includes('function ' + fn), RENDERER,
      `module points at render: ${fn}, but function ${fn}() is not defined`);
  });
  done(`${ids.length} modules defined, each with one delivery mode: ${ids.join(', ')}`);
}

// ── The modal focus contract ─────────────────────────────────────────────────
//
// Nothing offline can see a scroll lock, which is exactly why these textual
// checks exist. The bug they guard against left the page unscrollable with every
// other check green. See the comment above bcOpenModal.
section('Modal focus and scroll lock');
if (rendSrc) {
  assert(rendSrc.includes('function bcOpenModal'), RENDERER, 'missing bcOpenModal()');
  assert(rendSrc.includes('function bcCloseModal'), RENDERER, 'missing bcCloseModal()');
  assert(rendSrc.includes('bcTrapTab'), RENDERER, 'missing the Tab trap');

  // The idempotence guard. An unconditional push is the stranded-student bug.
  assert(/if\s*\(!BCModalStack\.some\(item\s*=>\s*item\.el\s*===\s*el\)\)\s*\{/.test(rendSrc), RENDERER,
    'bcOpenModal must guard the stack push on "not already open". An unconditional '
    + 'BCModalStack.push leaves the scroll lock on after Close.');

  // The release condition. Keying off an empty stack rather than "no visible
  // dialog" is the same bug wearing a different hat.
  assert(/if\s*\(!BCModalStack\.some\(item\s*=>\s*item\.el\.classList\.contains\('show'\)\)\)/.test(rendSrc), RENDERER,
    'the scroll lock must lift on "no visible dialog", not on "empty stack"');

  assert(/document\.body\.style\.overflow\s*=\s*''/.test(rendSrc), RENDERER,
    'bcCloseModal must restore document.body.style.overflow');

  // Every enlargeable image must be a real button. An onclick on its own is
  // mouse-only, which is how a lightbox stays unreachable by keyboard.
  assert(/class="enlargeable"/.test(rendSrc), RENDERER, 'no enlargeable image markup found');
  assert(/<button type="button" class="enlargeable"/.test(rendSrc), RENDERER,
    'enlargeable images must be <button> elements, not a div with an onclick');
  assert(/aria-label="Enlarge/.test(rendSrc), RENDERER,
    'an enlargeable image must carry an aria-label naming the picture');
  done('open/close, tab trap, idempotence guard, visible-dialog release, button lightbox');
}

// ── The deck controls ─────────────────────────────────────────────────────────
section('Background deck');
if (rendSrc) {
  assert(rendSrc.includes('function wireDeckControls'), RENDERER, 'missing wireDeckControls()');
  assert(/if\s*\(!host\s*\|\|\s*byId\('deck-prev'\)\)\s*return/.test(rendSrc), RENDERER,
    'wireDeckControls must guard on its own id, or a re-render doubles every button');
  assert(rendSrc.includes('function backToModules'), RENDERER, 'missing backToModules()');
  assert(/preventScroll:\s*true/.test(rendSrc), RENDERER,
    'backToModules must focus with preventScroll so the smooth scroll is the only movement');
  assert(/ArrowLeft/.test(rendSrc) && /ArrowRight/.test(rendSrc), RENDERER,
    'the deck must respond to the left and right arrow keys');
  assert(/Card \$\{deckIndex \+ 1\} of \$\{cards\.length\}/.test(rendSrc), RENDERER,
    'the deck must show a "Card N of M" counter');
  done('injected controls, id guard, arrow keys, counter, Back to Modules');
}

// ── The record footer contract ────────────────────────────────────────────────
//
// Three files have to agree: this renderer writes the footer, canvas-parse-core
// reads it, and the two must use the same tokens. A rename on one side reports
// every submission as unparseable, or worse, as empty.
section('Canvas record footer');
const PARSER = path.join(ROOT, 'scripts', 'lib', 'canvas-parse-core.js');
const parserSrc = read(PARSER);
if (rendSrc && parserSrc) {
  assert(rendSrc.includes("'#BHV|v='"), RENDERER, 'renderer must emit the #BHV| manifest header');
  assert(rendSrc.includes("'#BHR|i='"), RENDERER, 'renderer must emit #BHR| record lines');
  assert(parserSrc.includes('RE_HEADER = /#BHV'), PARSER, 'parser must read the #BHV| header');
  assert(parserSrc.includes('RE_RECORD = /#BHR'), PARSER, 'parser must read #BHR| record lines');

  // The sentinel is the one token that differs between the two courses, so the
  // parser has to accept both and the renderer has to emit this course's.
  assert(/BC_RECORD_OPEN = ["']--- BECURRENT RECORD/.test(rendSrc), RENDERER,
    'renderer must open the footer with the BECURRENT sentinel');
  assert(/RE_SENTINEL = \/---\\s\*\(\?:BECURRENT\|BEHISTORICAL\) RECORD\//.test(parserSrc), PARSER,
    'parser must accept both course sentinels, or one course stops parsing');

  // The denominator. A hard-coded 8 would report a week with no brief yet as
  // three responses short, which is worse than no count at all.
  assert(rendSrc.includes('function expectedCaptureCount'), RENDERER, 'missing expectedCaptureCount()');
  assert(/expected:\s*expectedCaptureCount\(\)/.test(rendSrc), RENDERER,
    'the footer must declare expected from expectedCaptureCount(), never a literal');

  // Paragraph structure is the one corruption the hash cannot catch, because the
  // hash normalizes whitespace on purpose. So the response must go out as
  // sibling <p> elements and never as <br>.
  assert(rendSrc.includes('function bcParagraphsHtml'), RENDERER, 'missing bcParagraphsHtml()');
  assert(/split\(\/\\n\{2,\}\//.test(rendSrc), RENDERER,
    'bcParagraphsHtml must split on blank lines so a blank line survives Canvas');
  done('shared machine grammar, per-course sentinel, computed denominator, paragraph split');
}

// ── One writer of the record grammar ─────────────────────────────────────────
//
// Two surfaces build a paste now: the week page's Gather panel and the Brief's own,
// which for a unit block is the ONLY route its answers have to Canvas. Both have to
// write the footer one parser reads, so the grammar lives in
// scripts/lib/canvas-record-block.js and is inlined into both.
//
// Two copies would mean two answers to "did this student edit their work" depending
// on which button the student pressed, with nothing able to say which had drifted.
// That is the failure that lost BeHistorical's capture block twice, so it is
// asserted here rather than trusted to a comment.
section('One record-grammar writer');
{
  const { recordBlockSource } = require('./lib/canvas-record-block');
  const shared = recordBlockSource('');

  const drift = spawnSync(process.execPath,
    [path.join(ROOT, 'scripts', 'build-canvas-record.js'), '--check'],
    { cwd: ROOT, encoding: 'utf8' });
  assert(drift.status === 0, RENDERER,
    'the inlined record block has drifted from scripts/lib/canvas-record-block.js. '
    + 'Run: node scripts/build-canvas-record.js');

  // And the briefs carry the same source. Asserting only the renderer would leave
  // the half-contract, which is the dangerous half.
  const { captureBlock: cb } = require('./lib/brief-capture-block');
  assert(cb('w00', 1, '').includes(recordBlockSource('  ')),
    path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
    'the emitted capture block does not carry the shared record grammar');

  // The Brief's denominator is its own question count, and it must be computed the
  // same way the week page computes its own: never a literal.
  assert(/expected:\s*IDS\.length/.test(cb('w00', 3, '')),
    path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
    "the brief footer must declare expected from IDS.length, never a literal");

  // The shared block is the thing both surfaces now depend on for the tokens the
  // parser matches, so it has to carry them itself rather than assume a caller does.
  const SHARED_TOKENS = ["'#BHV|v='", "'#BHR|i='", 'BECURRENT RECORD', 'function bcHash'];
  SHARED_TOKENS.forEach(token => {
    assert(shared.includes(token), path.join(ROOT, 'scripts/lib/canvas-record-block.js'),
      `the shared record block is missing ${token}`);
  });
  done('one grammar, inlined into the renderer and into every brief');
}

// ── Gather All My Work, on the brief ─────────────────────────────────────────
//
// A unit block Brief is opened straight off the unit page with no week shell around
// it, so its own Gather panel is the only route those answers have to Canvas. A
// brief that renders the buttons but carries no handler behind them is the dead
// button failure, and one that carries the handler but no buttons is unreachable
// work. Both directions are asserted, per brief, below in the capture-block pass.
section('Brief gather panel');
{
  const { captureBlock: cb } = require('./lib/brief-capture-block');
  const emitted = cb('w00', 3, '');
  ['gatherBriefWork', 'copyBriefWork'].forEach(fn => {
    assert(emitted.includes('window.' + fn + ' ='),
      path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
      `the capture block must define ${fn}()`);
  });

  // Both clipboard flavours. text/html is the only thing that carries the bold
  // question and the italic response into Canvas; text/plain is what the record
  // footer has to survive in, and what a locked-down device falls back to.
  assert(emitted.includes("'text/html'") && emitted.includes("'text/plain'"),
    path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
    'the copy must write both text/html and text/plain, or Canvas loses the formatting');
  assert(emitted.includes("bcParagraphsHtml(r.text, 'em')"),
    path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
    "the student's response must be emitted in italics, so the teacher can tell it "
    + 'from the prompt above it');
  done('gather and copy defined, both clipboard flavours, response in italics');
}

// ── The brief capture block ───────────────────────────────────────────────────
//
// This is the only path by which the three brief answers reach Canvas, and it
// has gone missing silently in the sibling repo twice. Four things are checked,
// because the version of this failure that leaves every other check green is the
// one where the block is present but a single file disagrees about the key.
section('Brief capture block');
const { captureBlock, STORAGE_PREFIX } = require('./lib/brief-capture-block');

const weekBriefFiles = [];
weekDirs.forEach(dir => {
  glob(path.join(ROOT, dir), /^brief-week-\d{2}-.*\.html$/)
    .filter(f => !f.endsWith('-capture.html'))
    .forEach(f => weekBriefFiles.push(f));
});

// Unit briefs. A unit carries a Brief only for the blocks that need a reading, so
// there is deliberately no expected count here: Social Media has none for Block 1
// (a slide deck and a paper trace) or Block 2 (a film).
const unitBriefFiles = [];
unitDirs.forEach(dir => {
  glob(path.join(ROOT, dir), /^block-\d{2}-brief-.*\.html$/)
    .filter(f => !f.endsWith('-capture.html'))
    .forEach(f => unitBriefFiles.push(f));
});

const briefFiles = weekBriefFiles.concat(unitBriefFiles);

assert(weekBriefFiles.length === weekDirs.length, ROOT,
  `expected one brief per week, found ${weekBriefFiles.length} for ${weekDirs.length} weeks`);

briefFiles.forEach(file => {
  const src = read(file);
  if (!src) { err(file, 'brief not readable'); return; }

  // Hyphens allowed: unit keys look like `sm-b3`, week keys like `w01`.
  const weekKey = (src.match(/var KEY = "becurrent-brief-([a-z0-9-]+)"/) || [])[1];
  if (!assert(!!weekKey, file, 'no capture block, or its storage key is unreadable. '
      + 'Without it the brief answers never reach Canvas.')) return;

  // Byte-identical to what the lib produces, so a hand-edit inside a generated
  // brief cannot survive.
  const count = (src.match(/class="question-item"/g) || []).length;
  const aiUrl = (src.match(/var AI_URL = "([^"]*)"/) || [])[1] || '';
  const expected = captureBlock(weekKey, count, aiUrl);
  assert(src.includes(expected), file,
    'the capture block is not byte-identical to scripts/lib/brief-capture-block.js. '
    + 'Never hand-edit it, change the lib and rebuild.');

  // How MANY questions a Brief carries is a teaching decision, not a contract, so
  // it is not asserted. What is asserted is that every question actually present is
  // wired to the capture block — an unwired question is a student answer that
  // silently never reaches Canvas, which is the failure this section exists for.
  assert(count >= 1, file, 'a brief with no question-item blocks captures nothing');
  for (let i = 1; i <= count; i++) {
    assert(src.includes(`id="answer-q${i}"`), file, `missing textarea id="answer-q${i}"`);
    assert(src.includes(`id="question-q${i}"`), file, `missing prompt id="question-q${i}"`);
    assert(src.includes(`id="confidence-q${i}"`), file, `missing confidence row id="confidence-q${i}"`);
  }

  // The Gather panel, both halves. The buttons with no handler is a dead button; the
  // handler with no ids to write into is work the student can never retrieve. A unit
  // block Brief has no other route to Canvas at all, so a missing panel there is
  // lost work rather than an inconvenience.
  assert(src.includes('onclick="gatherBriefWork()"'), file,
    'no Gather All My Work button. For a unit block brief this is the only route to Canvas.');
  assert(src.includes('onclick="copyBriefWork()"'), file, 'no Copy to Clipboard button');
  assert(src.includes('id="brief-gather-output"'), file,
    'the gather buttons have nowhere to write: missing #brief-gather-output');
  assert(src.includes('id="brief-gather-status"'), file,
    'missing #brief-gather-status, so a short gather cannot tell the student');

  // The output has to be a div, not a textarea. A textarea can only ever hold plain
  // text, which loses the bold question and the italic response the whole paste is
  // shaped around, and it also loses the rendered selection that a manual Ctrl-C
  // depends on where the clipboard API is blocked.
  assert(!/<textarea[^>]*id="brief-gather-output"/.test(src), file,
    '#brief-gather-output must be a div, not a textarea, or the formatting is lost');

  // Every confidence button carries its word. The number alone is the legend-in-your-
  // head version this replaced, and the word is also what the Canvas paste prints.
  const pills = (src.match(/class="conf-word"/g) || []).length;
  assert(pills === count * 5, file,
    `expected ${count * 5} labelled confidence buttons, found ${pills}`);
});
done(`${briefFiles.length} brief${briefFiles.length === 1 ? '' : 's'} carrying an identical capture block`);

// ── The storage key, agreed by four files ────────────────────────────────────
//
// The half-contract is the dangerous one. Asserting the briefs write the prefix
// proves nothing if the renderer was changed to read a different one: every
// structural check stays green and every answer is lost.
section('Storage key agreement');
assert(STORAGE_PREFIX === 'becurrent-brief-', path.join(ROOT, 'scripts/lib/brief-capture-block.js'),
  `STORAGE_PREFIX is '${STORAGE_PREFIX}', expected 'becurrent-brief-'`);
if (rendSrc) {
  assert(rendSrc.includes("'becurrent-brief-'"), RENDERER,
    "the renderer must read the 'becurrent-brief-' prefix the capture block writes");
  assert(rendSrc.includes("'becurrent-week-'"), RENDERER,
    "the renderer must namespace its own slots under 'becurrent-week-'");
}
done('capture block writes it, renderer reads it, prefix pinned in both');

// ── Week shells ───────────────────────────────────────────────────────────────
//
// Only the ids WITHOUT which a student loses work or gets stranded. The earlier
// version required all 26 ids the renderer can write into, which meant a shell
// could not omit the background deck or the lightbox even on a day that has
// neither — a code of daily conduct rather than a contract.
//
// A missing decorative id leaves a blank section, which is visible and fixable.
// A missing id from this list is not: no #pop-body and every module opens empty,
// no #gather-panel and there is no route to Canvas at all.
const REQUIRED_IDS = [
  'module-grid',    // no modules render without it
  'gather-panel',   // the only route to Canvas
  'pop-modal',      // every module opens into it
  'pop-body'
];

section('Week shells');
weekDirs.forEach(dir => {
  const file = path.join(ROOT, dir, 'index.html');
  const src = read(file);
  if (!src) { err(file, 'week shell missing'); return; }

  REQUIRED_IDS.forEach(id => {
    assert(src.includes(`id="${id}"`), file, `missing required id="${id}"`);
  });

  // The data file has to load before the renderer, or the renderer finds no week.
  const di = src.search(/assets\/data\/week-\d{2}\.js/);
  const ri = src.indexOf('becurrent-week-renderer-v1.js');
  assert(di > -1, file, 'no week data file loaded');
  assert(ri > -1, file, 'renderer not loaded');
  assert(di > -1 && ri > -1 && di < ri, file,
    'load order: the week data file must load BEFORE becurrent-week-renderer-v1.js');

  assert(src.includes('assets/css/becurrent.css'), file, 'system stylesheet not linked');

  // How many roadmap steps a page shows, and whether it shows one at all, is a
  // teaching decision. Not asserted.

  // Any dialog the page DOES have must declare itself to assistive tech. Absence
  // is fine; a dialog that traps a screen-reader user without announcing itself is
  // not, and that is invisible unless you are using a screen reader.
  ['pop-modal', 'background-modal', 'lightbox'].forEach(id => {
    if (!src.includes(`id="${id}"`)) return;
    const tag = (src.match(new RegExp(`<div class="[^"]*" id="${id}"[^>]*>`)) || [])[0] || '';
    assert(/role="dialog"/.test(tag), file, `#${id} must carry role="dialog"`);
    assert(/aria-modal="true"/.test(tag), file, `#${id} must carry aria-modal="true"`);
  });
});
done(`${weekDirs.length} shell${weekDirs.length === 1 ? '' : 's'}, ${REQUIRED_IDS.length} required ids each`);

// ── Brief structure ───────────────────────────────────────────────────────────
//
// Four blocks, not twenty-two. A Brief without a vocabulary strip, a callout, or a
// BeReady takeaway is a Brief that did not need one — that is a writing decision.
// What is asserted is the frame a student needs to read and submit at all.
//
// The AI coach builder is deliberately NOT here. It is optional and currently
// absent from every brief; see scripts/lib/brief-capture-block.js.
section('Brief structure');
const BRIEF_BLOCKS = [
  ['class="brief-title"', 'an h1 title'],
  ['class="brief-body"', 'a reading body'],
  ['class="check-section"', 'a check section, or the questions have nowhere to live'],
  ['class="page-footer-note"', 'the submission note telling students where work goes']
];
briefFiles.forEach(file => {
  const src = read(file);
  if (!src) return;
  BRIEF_BLOCKS.forEach(([needle, label]) => {
    assert(src.includes(needle), file, `missing ${label} (${needle})`);
  });
  assert(src.includes('becurrent-brief.css'), file, 'brief stylesheet not linked');
  // Abbreviated class names were a real source of drift in the sibling repo.
  assert(!/class="(cs|qi|mf|rt)"/.test(src), file,
    'abbreviated CSS class names are prohibited, use the canonical full names');
});
done(`${BRIEF_BLOCKS.length} load-bearing blocks per brief`);

// ── Capture wrappers ──────────────────────────────────────────────────────────
//
// Every brief is delivered through a wrapper, and the data file must point at
// the wrapper. Pointing at the brief itself leaves the AI coach button dead,
// because most briefs render it with no onclick and rely on the interception.
section('Capture wrappers and embed targets');
briefFiles.forEach(file => {
  const wrapper = file.replace(/\.html$/, '-capture.html');
  if (!assert(fs.existsSync(wrapper), file, 'no capture wrapper beside this brief')) return;

  const wsrc = read(wrapper);
  assert(/id="brief-frame"/.test(wsrc), wrapper, 'wrapper has no #brief-frame iframe');
  assert(wsrc.includes(path.basename(file)), wrapper,
    `wrapper iframe does not point at ${path.basename(file)}`);

  // Escape cannot cross a document boundary. Without this forwarder a student
  // typing inside the brief cannot close the modal that holds it, and no offline
  // check other than this one can see that.
  assert(wsrc.includes("event.key !== 'Escape'"), wrapper,
    'wrapper must forward Escape to the parent, or the brief traps the student');

  // The coach interceptor is required only when a coach exists. A brief renders
  // that button with no onclick of its own, so a URL with no interceptor is a dead
  // button — but no URL and no interceptor is correct.
  const briefSrc = read(file) || '';
  if (briefSrc.includes('id="ai-output"')) {
    assert(wsrc.includes('open ai coach'), wrapper,
      'this brief renders a coach button, so its wrapper must intercept the click');
  }
});

weekDirs.forEach(dir => {
  const nn = dir.slice(-2);
  const dataFile = path.join(ROOT, 'assets', 'data', `week-${nn}.js`);
  const src = read(dataFile);
  if (!assert(!!src, dataFile, 'week data file missing')) return;

  const embed = (src.match(/"embedUrl":\s*"([^"]*)"/) || [])[1];
  assert(!!embed, dataFile, 'no brief.embedUrl in the data file');
  if (embed) {
    assert(embed.endsWith('-capture.html'), dataFile,
      `embedUrl must point at the capture wrapper, found '${embed}'`);
    assert(fs.existsSync(path.join(ROOT, dir, embed)), dataFile,
      `embedUrl target does not exist: ${dir}/${embed}`);
  }
  assert(/"weekKey":\s*"w\d+"/.test(src), dataFile, 'no meta.weekKey in the data file');
  assert(src.includes('window.BECURRENT_WEEK'), dataFile, 'data file must set window.BECURRENT_WEEK');
  assert(src.includes('GENERATED by scripts/build-weeks.js'), dataFile,
    'data file is missing its generated-file banner');
});
done(`${briefFiles.length} wrapper${briefFiles.length === 1 ? '' : 's'}, ${weekDirs.length} embed target${weekDirs.length === 1 ? '' : 's'} resolved`);

// ── Student work never leaves the device ─────────────────────────────────────
//
// Canvas is the only channel. A form post or a fetch of student writing to a
// third party would be a privacy problem that no visual check would catch, so it
// is asserted rather than trusted.
section('No capture channel but Canvas');
const studentPages = [];
weekDirs.concat(unitDirs).forEach(dir => {
  glob(path.join(ROOT, dir), /\.html$/).forEach(f => studentPages.push(f));
});
studentPages.push(path.join(ROOT, 'index.html'));
[RENDERER].forEach(f => studentPages.push(f));

studentPages.forEach(file => {
  const src = read(file);
  if (!src) return;
  assert(!/<form[^>]*\saction=/i.test(src), file,
    'a <form action> on a student page would submit work off-device. Canvas is the only channel.');
  assert(!/\bfetch\s*\(/.test(src), file,
    'no fetch() on a student page: student writing must never be sent anywhere');
  assert(!/XMLHttpRequest/.test(src), file,
    'no XMLHttpRequest on a student page: student writing must never be sent anywhere');
  assert(!/docs\.google\.com\/forms/.test(src), file,
    'Google Forms are not a capture channel in this course');
});

// No other course's join code, ever. The AP World MagicSchool room was carried in
// here by the initial port; it is a different bot for a different class, and a
// student-facing link into it is a link into the wrong room. When BeCurrent has its
// own bot, set aiCoachUrl in the content module — a joinCode belongs in exactly one
// place, never pasted across repos.
const codeCarriers = studentPages.concat([
  path.join(ROOT, 'scripts', 'lib', 'week-content', 'week-01.js')
], fs.existsSync(path.join(ROOT, 'scripts', 'lib', 'unit-content'))
  ? glob(path.join(ROOT, 'scripts', 'lib', 'unit-content'), /\.js$/) : []);

codeCarriers.forEach(file => {
  const src = read(file);
  if (!src) return;
  assert(!/joinCode=[A-Za-z0-9]+/.test(src), file,
    'a MagicSchool joinCode is hardcoded here. BeCurrent has no bot yet, and the '
    + 'AP World code must never be carried into this repo.');
});
done(`${studentPages.length} student-facing files carry no off-device capture`);

// ── This is not an AP course ─────────────────────────────────────────────────
//
// BeCurrent is an elective that runs 9th through 12th grade in one room, with a wide
// spread of reading and writing levels in it. AP framing does two wrong things at
// once: it is factually untrue of this course, and it tells a struggling 9th grader
// that the work is pitched at somebody else.
//
// It is checked rather than trusted because the port from BeHistorical carried it in
// once already, as 'AP Skill Parallel' callouts on three briefs, and the same route
// is open every time a lesson is adapted across from that repo. The skill NAMES stay
// — Sourcing, Framing, Causation, Corroboration are what this course teaches, and
// they belong to nobody.
//
// The word boundary matters: 'AP' as a standalone word, not 'APPLE' or 'gap'.
section('Not an AP course');
const AP_CARRIERS = studentPages.concat(
  glob(path.join(ROOT, 'scripts', 'lib', 'week-content'), /\.js$/),
  fs.existsSync(path.join(ROOT, 'scripts', 'lib', 'unit-content'))
    ? glob(path.join(ROOT, 'scripts', 'lib', 'unit-content'), /\.js$/) : [],
  [path.join(ROOT, 'scripts', 'lib', 'desk-content.js')]
);

AP_CARRIERS.forEach(file => {
  const src = read(file);
  if (!src) return;
  const hit = src.match(/\bAP\b(?!\s*World MagicSchool)|Advanced Placement/);
  assert(!hit, file,
    `"${hit ? hit[0] : ''}" appears here. BeCurrent is not an AP course: it is a 9-12 `
    + 'elective with a mixed skill range in one room. Name the skill instead, the way '
    + "'Skill Focus' does.");
});
done(`${AP_CARRIERS.length} files carry no AP framing`);

// ── Unit pages ────────────────────────────────────────────────────────────────
//
// A unit page is the only map of its arc, so two ways of losing it matter and
// neither is visible on the page itself:
//
//   1. The unit page exists but nothing links to it, so it is reachable only by
//      typing the URL. That is how the first version shipped.
//   2. A block card links a Brief that was never generated, which is a 404 for a
//      student who missed that block and came looking for the reading.
section('Unit pages');
const frontDoor = read(path.join(ROOT, 'index.html')) || '';
unitDirs.forEach(key => {
  const page = path.join(ROOT, key, 'index.html');
  if (!assert(fs.existsSync(page), page, 'unit has no index.html mapping its blocks')) return;

  assert(frontDoor.includes(`href="${key}/index.html"`), path.join(ROOT, 'index.html'),
    `nothing on the front door links ${key}/index.html, so the unit is orphaned`);

  const src = read(page) || '';
  // Every Brief link on the card list has to resolve. The generic link check would
  // catch a typo; this catches a block that lost its Brief while keeping its card.
  (src.match(/href="(block-\d{2}-brief-[^"]+)"/g) || []).forEach(hit => {
    const target = hit.replace(/^href="|"$/g, '');
    assert(fs.existsSync(path.join(ROOT, key, target)), page,
      `block card links ${target}, which was not generated`);
  });

  assert(/class="block-card"/.test(src), page, 'unit page lists no blocks');

  // A block may declare `withholdTitles`: names that must not appear on any
  // student-facing page in the unit. Social Media Block 2 uses it for the film.
  //
  // This is a teaching contract, not plumbing, and it is in the gate anyway because
  // breaking it is invisible and irreversible: the damage happens the moment a
  // student reads the title, and no amount of fixing the page afterwards puts the
  // surprise back. From the Block 1 script, on why the withholding matters, "the
  // second they know the title, half the room looks it up, reads that it's a
  // documentary about social media being bad, and walks into Block 2 already knowing
  // what they're supposed to conclude."
  const unitMod = (() => {
    const dir = path.join(ROOT, 'scripts', 'lib', 'unit-content');
    const hit = glob(dir, /\.js$/).find(f => {
      try { return require(f).meta.unitKey === key; } catch (e) { return false; }
    });
    try { return hit ? require(hit) : null; } catch (e) { return null; }
  })();

  (unitMod ? unitMod.blocks || [] : []).forEach(b => {
    (b.withholdTitles || []).forEach(title => {
      glob(path.join(ROOT, key), /\.html$/).concat([path.join(ROOT, 'index.html')])
        .forEach(f => {
          const body = read(f) || '';
          assert(!new RegExp(title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i').test(body), f,
            `"${title}" is withheld until ${b.block} has been taught, and it appears here. `
            + 'A student who reads it walks in already knowing what to conclude.');
        });
    });
  });
});
done(`${unitDirs.length} unit page${unitDirs.length === 1 ? '' : 's'}, linked from the front door`);

// ── The Desk ──────────────────────────────────────────────────────────────────
//
// The daily half of every block, and the one page a student opens more often
// than any other. Two things about it fail quietly.
//
// Orphaning: the Desk lives at daily/index.html and nothing else in the site
// links down into it, so if the front door drops the link the page still builds,
// still validates, and is reachable only by typing the URL. That is exactly how
// the first unit page shipped orphaned.
//
// A headline: per CLAUDE.md the Desk must never carry a story, because the page
// is generated once and served every class period for a year. A "for example"
// headline written in August is a fabricated one by September and a stale one by
// October, on the single page this course opens every single day.
section('The Desk');
const DESK_PAGE = path.join(ROOT, 'daily', 'index.html');
if (assert(fs.existsSync(DESK_PAGE), DESK_PAGE, 'daily/index.html is missing')) {
  assert(frontDoor.includes('href="daily/index.html"'), path.join(ROOT, 'index.html'),
    'nothing on the front door links daily/index.html, so the Desk is orphaned');

  const deskSrc = read(DESK_PAGE) || '';
  const desk = require('./lib/desk-content');

  // Nobody speaks to the room. This is a hard constraint set by the teacher on
  // the basis of the room's IEP and 504 load, and it is exactly the kind of rule
  // that regresses quietly: an oral step reads as a perfectly sensible edit to
  // anyone who was not in the conversation, breaks nothing technically, and is
  // discovered by a student being asked to present.
  //
  // Enforced here and NOT announced on the page. An earlier version required the
  // page to promise students they would never present, which turned an ordinary
  // absence into a special accommodation and pointed at exactly the students it
  // was meant to protect. The design carries the constraint; the room does not
  // need to be told about it.
  const SPEAKING = /\b(present to the class|presentation|report out|share out|out loud to the class|oral report|call on you|called on)\b/i;
  [['meta.deck', desk.meta.deck],
    ...(desk.routine || []).flatMap((s, i) => [[`routine[${i}].what`, s.what], [`routine[${i}].why`, s.why]]),
    ['accountability.daily', (desk.accountability || {}).daily]
  ].forEach(([where, text]) => {
    assert(!SPEAKING.test(String(text || '')), path.join(ROOT, 'scripts', 'lib', 'desk-content.js'),
      `${where} asks a student to speak to the room. The daily half is filed, never spoken; `
      + 'see the header of desk-content.js before changing this.');
  });

  (desk.beats || []).forEach(b => {
    assert(deskSrc.includes(`>${b.name}<`), DESK_PAGE, `the ${b.name} beat is not on the page`);
  });
  (require('./lib/desk-content').resources || []).forEach(r => {
    assert(deskSrc.includes(`href="${r.url}"`), DESK_PAGE, `${r.name} is not linked`);
    assert(new RegExp(`href="${r.url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[^>]*rel="noopener noreferrer"`).test(deskSrc),
      DESK_PAGE, `${r.name} opens without rel="noopener noreferrer"`);
  });
  done(`${(require('./lib/desk-content').beats || []).length} beats, `
    + `${(require('./lib/desk-content').resources || []).length} standing sources, linked from the front door`);
}

// ── Video ─────────────────────────────────────────────────────────────────────
//
// Whether a lesson has video, and how much, is a teaching decision. Two things
// about it are not, and both fail silently:
//
//   1. A clip with no url is a card a student clicks that goes nowhere.
//   2. A lesson that DEFINES clips but whose shell has no #video-clips container
//      renders them nowhere at all. The page looks fine and the video is gone,
//      which for this room's IEP/504 load is the most expensive silent failure
//      available.
section('Video');
let clipCount = 0;

function checkClips(clips, file, where) {
  (clips || []).forEach((v, i) => {
    clipCount++;
    assert(!!(v && v.url), file,
      `${where} clip ${i + 1} has no url. A clip card with no link goes nowhere.`);
    assert(!!(v && v.title), file,
      `${where} clip ${i + 1} has no title. A clip card is headed by its own title.`);
  });
}

// Week content, and the shell that has to be able to show it.
weekDirs.forEach(dir => {
  const nn = dir.slice(-2);
  const contentFile = path.join(ROOT, 'scripts', 'lib', 'week-content', `week-${nn}.js`);
  if (!fs.existsSync(contentFile)) return;
  let week = null;
  try { week = require(contentFile); } catch (e) { err(contentFile, 'content module not loadable'); return; }

  checkClips(week.videos, contentFile, 'week');

  if ((week.videos || []).length) {
    const shell = path.join(ROOT, dir, 'index.html');
    const src = read(shell) || '';
    assert(src.includes('id="video-clips"'), shell,
      'this lesson defines video clips, but the shell has no #video-clips container, '
      + 'so they render nowhere.');
  }
});

// Unit blocks.
(() => {
  const dir = path.join(ROOT, 'scripts', 'lib', 'unit-content');
  if (!fs.existsSync(dir)) return;
  glob(dir, /\.js$/).forEach(f => {
    let unit = null;
    try { unit = require(f); } catch (e) { err(f, 'unit content not loadable'); return; }
    (unit.blocks || []).forEach(b => checkClips(b.videos, f, `${b.block || 'block'}`));
  });
})();

// The renderer must hide the container rather than leave it empty. An empty
// section reads to a student as something that failed to load.
if (rendSrc) {
  assert(rendSrc.includes('function renderVideos'), RENDERER, 'missing renderVideos()');
  assert(/host\.hidden = true/.test(rendSrc), RENDERER,
    'renderVideos must hide the container when there are no clips, not leave it empty');
}
done(`${clipCount} clip${clipCount === 1 ? '' : 's'} defined, container wiring checked`);

// ── Favicon ───────────────────────────────────────────────────────────────────
//
// Every student-facing page links it, so no page falls back to the browser's
// unprompted /favicon.ico request. That request goes to the DOMAIN root, which on
// a project Pages site belongs to a different repo entirely and can never be
// satisfied from here, so an explicit link is the only fix rather than a nicety.
section('Favicon');
const FAVICON = path.join(ROOT, 'assets', 'favicon.svg');
assert(fs.existsSync(FAVICON), FAVICON, 'assets/favicon.svg is missing');
studentPages.filter(f => f.endsWith('.html')).forEach(file => {
  const src = read(file);
  if (!src) return;
  assert(/<link rel="icon" href="[^"]*assets\/favicon\.svg" type="image\/svg\+xml">/.test(src), file,
    'no favicon link. Every student-facing page must link assets/favicon.svg.');
});
done(`linked on ${studentPages.filter(f => f.endsWith('.html')).length} pages`);

// ── The brand file ───────────────────────────────────────────────────────────
//
// becurrent-brand.css is the only file that defines a token, and every page has
// to link it. Both halves of that fail quietly enough to be worth a check.
//
// A page that links becurrent.css and forgets the brand file resolves every
// custom property to nothing: no palette, no faces, a page that is technically
// complete and looks like a 1996 term paper. Nothing else in this suite would
// notice, because every id, block and capture wire is still exactly where it
// should be.
//
// A second :root in a component stylesheet is the quieter one. It works, so it
// survives, and the course ends up with two reds that agree until the day one of
// them is edited. That is the same failure as two copies of the capture block,
// in a place nobody thinks to look.
section('The brand file');
const BRAND = path.join(ROOT, 'assets', 'css', 'becurrent-brand.css');
assert(fs.existsSync(BRAND), BRAND, 'assets/css/becurrent-brand.css is missing');

const brandSrc = read(BRAND) || '';
['--signal', '--signal-deep', '--black-900', '--ink', '--focus', '--display', '--body', '--ui']
  .forEach(token => {
    assert(new RegExp(`${token}\\s*:`).test(brandSrc), BRAND,
      `the brand file defines no ${token}`);
  });

// Every token a component asks for has to exist. An undefined custom property
// does not fall back to anything: `color: var(--gone)` inherits, and
// `border-top: 4px solid var(--gone)` draws the border in currentColor. Both
// render as a page that looks broadly right, which is why removing a token and
// leaving one component still asking for it survives a visual check.
//
// This is the check the red-and-black recolour needed. --cool was referenced in
// 35 places across two stylesheets; missing one would have left a lone teal rule
// resolving to whatever the surrounding text colour happened to be.
const defined = new Set((brandSrc.match(/(--[a-z0-9-]+)\s*:/g) || [])
  .map(m => m.replace(/\s*:$/, '')));
['becurrent.css', 'becurrent-brief.css'].forEach(name => {
  const file = path.join(ROOT, 'assets', 'css', name);
  const src = (read(file) || '').replace(/\/\*[\s\S]*?\*\//g, '');
  const used = new Set((src.match(/var\(\s*(--[a-z0-9-]+)/g) || [])
    .map(m => m.replace(/^var\(\s*/, '')));
  [...used].sort().forEach(token => {
    assert(defined.has(token), file,
      `${name} uses ${token}, which becurrent-brand.css does not define. `
      + 'An undefined custom property does not fall back, it resolves to nothing.');
  });
});

// The same failure one layer down. A @font-face pointing at a file that is not
// there is silent: the browser drops to the next family in the stack and the
// page renders in Georgia or Arial, correctly, in the wrong typeface.
(brandSrc.match(/url\("([^"]+\.woff2)"\)/g) || []).forEach(m => {
  const rel = m.replace(/^url\("/, '').replace(/"\)$/, '');
  const full = path.resolve(path.dirname(BRAND), rel);
  assert(fs.existsSync(full), BRAND,
    `@font-face points at ${rel}, which does not exist. A missing face does not `
    + 'error, it falls back to a system font and the page is simply the wrong type.');
});

// Only pages that carry a component stylesheet. A capture wrapper is a bare
// iframe host with no stylesheet of any kind, and requiring one there would be
// asking it to download three fonts to render nothing.
let brandLinked = 0;
studentPages.filter(f => f.endsWith('.html')).forEach(file => {
  const src = read(file);
  if (!src) return;
  if (!/becurrent(-brief)?\.css/.test(src)) return;
  brandLinked += 1;
  assert(/<link rel="stylesheet" href="[^"]*assets\/css\/becurrent-brand\.css">/.test(src), file,
    'no brand stylesheet. Every page that links a component stylesheet must link '
    + 'assets/css/becurrent-brand.css first, or every colour and face on it resolves to nothing.');
});

['becurrent.css', 'becurrent-brief.css'].forEach(name => {
  const file = path.join(ROOT, 'assets', 'css', name);
  const src = read(file) || '';
  assert(!/--[a-z0-9-]+\s*:/.test(src.replace(/\/\*[\s\S]*?\*\//g, '')), file,
    `${name} defines a custom property. Tokens live only in becurrent-brand.css.`);
});
done(`${brandLinked} pages linked, tokens defined once`);

// ── The wordmark lockups ─────────────────────────────────────────────────────
//
// Every page renders the wordmark as an <img> with explicit width and height,
// and those numbers have to match the file. If they drift the browser reserves
// the wrong box and the mark is letterboxed or stretched inside it, which looks
// like a rendering bug rather than a stale attribute.
//
// This is not hypothetical, and it has happened on every redraw: 4889x810, then
// 4101x716, then 7101x733 when the mark moved to Cinzel. Each time, ten
// hardcoded pairs across four generators had to move with it, and nothing else
// in this suite would have caught a single one.
section('Wordmark lockups');
const MARKS = ['becurrent-wordmark.svg', 'becurrent-wordmark-ink.svg'];
const markDims = {};
MARKS.forEach(name => {
  const full = path.join(ROOT, 'assets', 'images', 'brand', name);
  const src = read(full);
  if (!assert(!!src, full, 'wordmark file is missing')) return;
  const w = (src.match(/<svg[^>]*\swidth="([\d.]+)"/) || [])[1];
  const h = (src.match(/<svg[^>]*\sheight="([\d.]+)"/) || [])[1];
  assert(!!w && !!h, full, 'wordmark has no intrinsic width and height');
  markDims[name] = { w, h };
});

let lockups = 0;
studentPages.filter(f => f.endsWith('.html')).forEach(file => {
  const src = read(file) || '';
  MARKS.forEach(name => {
    const dims = markDims[name];
    if (!dims) return;
    const re = new RegExp(`<img[^>]*brand/${name.replace('.', '\\.')}"[^>]*>`, 'g');
    (src.match(re) || []).forEach(tag => {
      lockups += 1;
      const w = (tag.match(/\swidth="(\d+)"/) || [])[1];
      const h = (tag.match(/\sheight="(\d+)"/) || [])[1];
      assert(w === dims.w && h === dims.h, file,
        `${name} is rendered at ${w}x${h} but the file is ${dims.w}x${dims.h}. `
        + 'The <img> dimensions must match the mark, or the browser reserves the wrong box.');
    });
  });
});
done(`${lockups} lockups, all matching the mark's own dimensions`);

// ── Image integrity ──────────────────────────────────────────────────────────
//
// A text file named .jpg renders as a broken frame, which reads to a student as
// the site failing. Magic bytes, not extensions.
section('Image integrity');
const MAGIC = {
  '.png': [[0x89, 0x50, 0x4e, 0x47]],
  '.jpg': [[0xff, 0xd8, 0xff]],
  '.jpeg': [[0xff, 0xd8, 0xff]],
  '.gif': [[0x47, 0x49, 0x46, 0x38]],
  '.webp': [[0x52, 0x49, 0x46, 0x46]]
};

function walkImages(dir) {
  if (!fs.existsSync(dir)) return;
  fs.readdirSync(dir, { withFileTypes: true }).forEach(entry => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) { walkImages(full); return; }
    const ext = path.extname(entry.name).toLowerCase();

    if (ext === '.svg') {
      const src = read(full) || '';
      // A viewBox alone leaves the intrinsic size undefined, and an <img>
      // holding one gets stretched until the picture is letterboxed off-screen.
      assert(/<svg[^>]*\swidth="[\d.]+"/.test(src) && /<svg[^>]*\sheight="[\d.]+"/.test(src), full,
        'an SVG must carry width and height on its root element, not a viewBox alone');
      assert(src.includes('<svg'), full, 'not an SVG');
      return;
    }

    const signatures = MAGIC[ext];
    if (!signatures) return;
    const buf = fs.readFileSync(full);
    const matched = signatures.some(sig => sig.every((b, i) => buf[i] === b));
    assert(matched, full, `magic bytes do not match ${ext}. Never commit a placeholder image file.`);
  });
}
walkImages(path.join(ROOT, 'assets', 'images'));
done('magic bytes checked, SVG intrinsic sizes checked');

// ── Local link integrity ─────────────────────────────────────────────────────
section('Local link integrity');
let linkCount = 0;
studentPages.filter(f => f.endsWith('.html')).forEach(file => {
  const src = read(file);
  if (!src) return;
  const re = /(?:href|src)="([^"#?][^"]*)"/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const url = m[1];
    if (/^(https?:|mailto:|data:|\/\/)/.test(url)) continue;
    linkCount++;
    const target = path.resolve(path.dirname(file), url.split(/[?#]/)[0]);
    assert(fs.existsSync(target), file, `dead local link: ${url}`);
  }
});
done(`${linkCount} local links resolved`);

// ── Summary ───────────────────────────────────────────────────────────────────

console.log(`\n${'─'.repeat(64)}`);
if (errors.length) {
  console.log(`${R}${W}${errors.length} problem${errors.length === 1 ? '' : 's'}${X} across ${checks} checks\n`);
  errors.forEach(e => console.log(`  ${R}✗${X} ${W}${e.file}${X}\n     ${e.message}`));
  console.log('');
  process.exit(1);
}
console.log(`${G}${W}All ${checks} structural checks passed.${X}`);
