#!/usr/bin/env node
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const {spawnSync}=require('child_process');
const ROOT=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const unit=require('../lib/unit-content/midterms');
assert.strictEqual(unit.meta.renderer,'video-first');
assert.strictEqual(unit.meta.code,'WP');
assert.strictEqual(unit.topics.length,5);
const page=read('midterms/block-01.html');
const index=read('midterms/index.html');
assert(page.includes('data-lesson="wp-t01"'));
assert(page.includes('id="teacher-flow"')&&page.includes('id="student-flow"'));
assert.strictEqual((page.match(/data-teacher-stage/g)||[]).length,6);
assert.strictEqual((page.match(/data-student-chapter/g)||[]).length,5);
assert.strictEqual((page.match(/data-slot=/g)||[]).length,3);
assert.strictEqual((page.match(/data-sort=/g)||[]).length,5);
assert(page.includes('id="gather-work"')&&page.includes('id="copy-preview"'));
assert(page.includes('video-first-record.js')&&page.includes('video-first.js'));
assert(index.includes('href="block-01.html"'));
assert(!index.includes('href="block-02.html"'));
for(const v of unit.topics[0].videos){assert(page.includes(v.url),'video not linked: '+v.title)}
const script=read('assets/js/video-first.js');
new vm.Script(script);
new vm.Script(read('assets/js/video-first-record.js'));
assert(script.includes('bcRecordManifest('),'Canvas record manifest missing');
assert(script.includes('bcRecordFooterHtml('),'Canvas HTML footer missing');
assert(!/\\bfetch\\s*\\(|XMLHttpRequest|<form\\s+action/i.test(page+script),'student page makes outbound request');
const r=spawnSync(process.execPath,['scripts/build-video-first.js','--check'],{cwd:ROOT,encoding:'utf8'});
assert.strictEqual(r.status,0,(r.stdout||'')+(r.stderr||''));
console.log('OK: video-first pilot, both modes, student captures, video links, and canonical record grammar.');
